language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - gcc-arm-none-eabi
            - libnewlib-arm-none-eabi
            - cmake
script:
  - cmake -DCMAKE_TOOLCHAIN_FILE=arm-none-eabi-gcc.cmake .
  - make