language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - gcc-arm-none-eabi
            - cmake
script:
  - cmake .
  - make