language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - gcc-arm-none-eabi
            - cmake
script:
  - export CC=arm-none-eabi-gcc
  - export CXX=arm-none-eabi-g++
  - cmake .
  - make