version: 2
jobs:
  build:
    docker:
      - image: debian:sid
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install -y cmake make arm-none-eabi-gcc
      - run:
          name: Compile
          command: cmake . && make