version: 2
jobs:
  build:
    docker:
      - image: fedora:26
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: dnf install -y cmake make arm-none-eabi-gcc-cs arm-none-eabi-gcc-cs-c++ arm-none-eabi-newlib unzip findutils
      - run:
          name: Compile
          command: cmake -DCMAKE_TOOLCHAIN_FILE=arm-none-eabi-gcc.cmake . && make