version: 2
jobs:
  build:
    docker:
      - image: debian:sid
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install -y cmake make gcc-arm-none-eabi
      - run:
          name: Compile
          command: export CC=arm-none-eabi-gcc && export CXX=arm-none-eabi-g++ && cmake . && make